services:
  migrate:
    image: ghcr.io/ddcat-ai/open-ai-canvas-backend:${CANVAS_IMAGE_TAG:-latest}

  backend:
    image: ghcr.io/ddcat-ai/open-ai-canvas-backend:${CANVAS_IMAGE_TAG:-latest}

  web:
    image: ghcr.io/ddcat-ai/open-ai-canvas-web:${CANVAS_IMAGE_TAG:-latest}

volumes:
  backend-data:
    external: true
    name: yingce_backend-data
  postgres-data:
    external: true
    name: yingce_postgres-data
  redis-data:
    external: true
    name: yingce_redis-data
